name: proxy-app
services:
  - type: web
    name: proxy-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: static
        name: proxy-app
        path: /
        preservePath: true
        redirect: false